# Generated by Django 4.2.6 on 2023-10-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='thread_pictures/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
