# Generated by Django 4.2.6 on 2023-10-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_thread_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='thread_pictures/'),
        ),
    ]
