# Generated by Django 4.2.6 on 2023-10-27 15:02

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_thread_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.subfolder_manage),
        ),
    ]
