# Generated by Django 4.2.6 on 2023-10-29 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_savedthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedthread',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='saved', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
